dapm_final/Areas/Admin/Controllers/AdminCustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using dapm_final.Models;
using PagedList.Core;

namespace dapm_final.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminCustomersController : Controller
    {
        private readonly FYProjectContext _context;

        public AdminCustomersController(FYProjectContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminCustomers
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var lsCustomers = _context.Customers
                .AsNoTracking()
                .Include(x => x.Location)
                .OrderByDescending(x => x.CreateDate);

            PagedList<Customer> models = new PagedList<Customer>(lsCustomers, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminCustomers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .Include(c => c.Location)
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Admin/AdminCustomers/Create
        public IActionResult Create()
        {
            ViewData["LocationId"] = new SelectList(_context.Locations, "LocationId", "LocationId");
            return View();
        }

        // POST: Admin/AdminCustomers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerId,FullName,Birthday,Avatar,Address,Email,Phone,LocationId,District,Ward,CreateDate,Password,Salt,LastLogin,Active")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationId"] = new SelectList(_context.Locations, "LocationId", "LocationId", customer.LocationId);
            return View(customer);
        }

        // GET: Admin/AdminCustomers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            ViewData["LocationId"] = new SelectList(_context.Locations, "LocationId", "LocationId", customer.LocationId);
            return View(customer);
        }

        // POST: Admin/AdminCustomers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CustomerId,FullName,Birthday,Avatar,Address,Email,Phone,LocationId,District,Ward,CreateDate,Password,Salt,LastLogin,Active")] Customer customer)
        {
            if (id != customer.CustomerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.CustomerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationId"] = new SelectList(_context.Locations, "LocationId", "LocationId", customer.LocationId);
            return View(customer);
        }

        // GET: Admin/AdminCustomers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .Include(c => c.Location)
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Admin/AdminCustomers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return _context.Customers.Any(e => e.CustomerId == id);
        }
    }
}

dapm_final/Areas/Admin/Views/AdminCustomers/Create.cshtml
@model dapm_final.Models.Customer

@{
    ViewData["Title"] = "Tạo mới khách hàng";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
} @* xong *@

@section Styles{
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang Chủ</a>
            <a asp-area="Admin" asp-controller="AdminCustomers" asp-action="Index" class="breadcrumb-item">Danh Sách Khách Hàng</a>
            <span class="breadcrumb-item active">Tạo Mới Khách Hàng</span>
        </nav>
    </div>
</div>


<form asp-controller="AdminCustomers" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-5">
            </div>
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Tạo Mới</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN KHÁCH HÀNG</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN SEO</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Birthday" class="control-label"></label>
                        <input asp-for="Birthday" class="form-control" />
                        <span asp-validation-for="Birthday" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label asp-for="Avatar" class="control-label"></label>
                            <input asp-for="Avatar" class="form-control" />
                            <span asp-validation-for="Avatar" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Address" class="control-label"></label>
                            <input asp-for="Address" class="form-control" />
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-6">
                            <label asp-for="Email" class="control-label"></label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group col-6">
                            <label asp-for="Phone" class="control-label"></label>
                            <input asp-for="Phone" class="form-control" />
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="LocationId" class="control-label"></label>
                        <input asp-for="LocationId" class="form-control" />
                        <span asp-validation-for="LocationId" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="form-group col-6">
                                <label asp-for="District" class="control-label"></label>
                                <input asp-for="District" class="form-control" />
                                <span asp-validation-for="District" class="text-danger"></span>
                            </div>
                        <div class="form-group col-6">
                                <label asp-for="Ward" class="control-label"></label>
                                <input asp-for="Ward" class="form-control" />
                                <span asp-validation-for="Ward" class="text-danger"></span>
                            </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="CreateDate" class="control-label"></label>
                        <input asp-for="CreateDate" class="form-control" />
                        <span asp-validation-for="CreateDate" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Salt" class="control-label"></label>
                        <input asp-for="Salt" class="form-control" />
                        <span asp-validation-for="Salt" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastLogin" class="control-label"></label>
                        <input asp-for="LastLogin" class="form-control" />
                        <span asp-validation-for="LastLogin" class="text-danger"></span>
                    </div>
                    <div class="form-group d-flex align-items-center">
                        <div class="switch m-r-10">
                            <input type="checkbox" asp-for="Active" checked="">
                            <label for="Active"></label>
                        </div>
                        <label>@Html.DisplayNameFor(model => model.Active)</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{

    <!-- page js -->
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/vendors/quill/quill.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Adminassets/summernote/summernote-bs4.js"></script>
    <script>

        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
}

dapm_final/Areas/Admin/Views/AdminCustomers/Delete.cshtml
@model dapm_final.Models.Customer

@{
    ViewData["Title"] = "Xác nhận xoá khách hàng";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
} @* xong *@

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang Chủ</a>
            <a asp-area="Admin" asp-controller="AdminCustomers" asp-action="Index" class="breadcrumb-item">Danh Sách Khách Hàng</a>
            <span class="breadcrumb-item active">Xác Nhận Xoá Khách Hàng</span>
        </nav>
    </div>
</div>

<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height:70px; width:70px">
                <img src="~/images/customer/Avatar.png" alt="Avatar" />
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.FullName</h4>
                <p class="text-muted m-b-0">ID: #@Model.CustomerId</p>
            </div>
        </div>
        <div class="m-b-15">
            <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminCustomers" asp-action="Edit" asp-route-id="@Model.CustomerId">Chỉnh Sửa</a>
        </div>
    </div>
</div>

<div class="card-body">
    <h4 class="card-title">Thông Tin Khách Hàng: @Model.FullName</h4>
    <div class="table-responsive">
        <table class="product-info-table m-t-20">
            <tbody>
                <tr>
                    <td>ID:</td>
                    <td class="text-dark font-weight-semibold">@Model.CustomerId</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.FullName):</td>
                    <td>@Html.DisplayFor(model => model.FullName)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Birthday):</td>
                    <td>@Html.DisplayFor(model => model.Birthday)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Address):</td>
                    <td>@Html.DisplayFor(model => model.Address)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Email):</td>
                    <td>@Html.DisplayFor(model => model.Email)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Phone):</td>
                    <td>@Html.DisplayFor(model => model.Phone)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.LocationId):</td>
                    <td>@Html.DisplayFor(model => model.LocationId)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.District):</td>
                    <td>@Html.DisplayFor(model => model.District)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Ward):</td>
                    <td>@Html.DisplayFor(model => model.Ward)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.CreateDate):</td>
                    <td>@Html.DisplayFor(model => model.CreateDate)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Password):</td>
                    <td>@Html.DisplayFor(model => model.Password)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Salt):</td>
                    <td> @Html.DisplayFor(model => model.Salt)s</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Avatar):</td>
                    <td>
                        @Html.DisplayFor(model => model.Avatar)
                    </td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.LastLogin):</td>
                    <td>@Html.DisplayFor(model => model.LastLogin)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Active)</td>
                    <td>
                        @if (Model.Active)
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" checked="" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                        else
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                    </td>
                </tr>
                <tr>
                    <td>
                        <form asp-controller="AdminCustomers" asp-action="Delete" asp-route-id="@Model.CustomerId">
                            <input type="hidden" asp-for="CustomerId" />
                            <input type="submit" value="Xác Nhận Xóa" class="btn btn-danger" />
                        </form>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

dapm_final/Areas/Admin/Views/AdminCustomers/Details.cshtml
@model dapm_final.Models.Customer

@{
    ViewData["Title"] = "Chi tiết khách hàng";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
} @* xong *@


<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang Chủ</a>
            <a asp-area="Admin" asp-controller="AdminCustomers" asp-action="Index" class="breadcrumb-item">Danh Sách Khách Hàng</a>
            <span class="breadcrumb-item active">Thông Tin Khách Hàng</span>
        </nav>
    </div>
</div>

<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height:70px; width:70px">
                <img src="~/images/customer/Avatar.png" alt="Avatar" />
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.FullName</h4>
                <p class="text-muted m-b-0">ID: #@Model.CustomerId</p>
            </div>
        </div>
        <div class="m-b-15">
            <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminCustomers" asp-action="Edit" asp-route-id="@Model.CustomerId">Chỉnh Sửa</a>
        </div>
    </div>
</div>

<div class="card-body">
    <h4 class="card-title">Thông Tin Khách Hàng: @Model.FullName</h4>
    <div class="table-responsive">
        <table class="product-info-table m-t-20">
            <tbody>
                <tr>
                    <td>ID:</td>
                    <td class="text-dark font-weight-semibold">@Model.CustomerId</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.FullName):</td>
                    <td>@Html.DisplayFor(model => model.FullName)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Birthday):</td>
                    <td>@Html.DisplayFor(model => model.Birthday)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Address):</td>
                    <td>@Html.DisplayFor(model => model.Address)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Email):</td>
                    <td>@Html.DisplayFor(model => model.Email)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Phone):</td>
                    <td>@Html.DisplayFor(model => model.Phone)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.LocationId):</td>
                    <td>@Html.DisplayFor(model => model.LocationId)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.District):</td>
                    <td>@Html.DisplayFor(model => model.District)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Ward):</td>
                    <td>@Html.DisplayFor(model => model.Ward)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.CreateDate):</td>
                    <td>@Html.DisplayFor(model => model.CreateDate)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Password):</td>
                    <td>@Html.DisplayFor(model => model.Password)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Salt):</td>
                    <td> @Html.DisplayFor(model => model.Salt)s</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Avatar):</td>
                    <td>
                        @Html.DisplayFor(model => model.Avatar)
                    </td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.LastLogin):</td>
                    <td>@Html.DisplayFor(model => model.LastLogin)</td>
                </tr>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Active)</td>
                    <td>
                        @if (Model.Active)
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" checked="" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                        else
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                    </td>
                </tr>

            </tbody>
        </table>
    </div>
</div>

dapm_final/Areas/Admin/Views/AdminCustomers/Index.cshtml
@using PagedList.Core.Mvc;
@model PagedList.Core.IPagedList<dapm_final.Models.Customer>

@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh Sách Khách Hàng - Trang " + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
} @* xong *@


<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang Chủ</a>
            <span class="breadcrumb-item active">Danh Sách Khách Hàng - Trang @CurrentPage</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-12">
                <div class="d-md-flex">
                    <div class="m-b-10 m-r-15">
                        <select class="custom-select" style="min-width: 180px;">
                            <option selected>Catergory</option>
                            <option value="all">All</option>
                            <option value="homeDeco">Home Decoration</option>
                            <option value="eletronic">Eletronic</option>
                            <option value="jewellery">Jewellery</option>
                        </select>
                    </div>
                    <div class="m-b-10">
                        <select class="custom-select" style="min-width: 180px;">
                            <option selected>Status</option>
                            <option value="all">All</option>
                            <option value="inStock">In Stock </option>
                            <option value="outOfStock">Out of Stock</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-6">
                        <div class="input-affix m-v-10">
                            <i class="prefix-icon anticon anticon-search opacity-04"></i>
                            <input id="keyword" name="keyword" type="text" class="form-control" placeholder="Tìm Kiếm Khách Hàng">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 text-right">
                <a class="btn btn-primary" asp-controller="AdminCustomers" asp-action="Create"><i class="anticon anticon-plus-circle m-r-5"></i><span>Thêm Khách Hàng</span></a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Họ Và Tên</th>
                        <th>Số Điện Thoại</th>
                        <th>Email</th>
                        <th>Địa Chỉ</th>
                        <th>Thao Tác</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>

                                <td>@item.CustomerId</td>
                                <td>@item.FullName</td>
                                <td>@item.Phone</td>
                                <td>@item.Email</td>
                                <td>@item.Address</td>
                                <td>
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCustomers" asp-action="Details" asp-route-id="@item.CustomerId">Chi Tiết</a>
                                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCustomers" asp-action="Edit" asp-route-id="@item.CustomerId">Sửa</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCustomers" asp-action="Delete" asp-route-id="@item.CustomerId">Xóa</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminCustomers" asp-action="Index"></pager>
                </ul>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $("#keyword").keyup(function () {
            console.log('Tuan3');
            var strkeyword = $('#keyword').val();
            $.ajax({
                url: '/Admin/Search/FindCutomer/',
                datatype: "json",
                type: "POST",
                data: { keyword: strkeyword },
                async: true,
                success: function (results) {
                    $("#records_table").html("");
                    $("#records_table").html(results);
                },
                error: function (xhr) {
                    alert('error');
                }
            });
        });
    </script>

}