dapm_final/Areas/Admin/Controllers/AdminRolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using dapm_final.Models;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace dapm_final.Areas.Admin.Controllers /*xong*/
{
    [Area("Admin")]
    public class AdminRolesController : Controller
    {
        private readonly FYProjectContext _context;
        public INotyfService _notyfService { get; }

        public AdminRolesController(FYProjectContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminRoles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Roles.ToListAsync());
        }

        // GET: Admin/AdminRoles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Admin/AdminRoles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminRoles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoleId,RoleName,Description")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                _notyfService.Success("Tạo mới thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Admin/AdminRoles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Admin/AdminRoles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoleId,RoleName,Description")] Role role)
        {
            if (id != role.RoleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Cập nhập thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.RoleId))
                    {
                        _notyfService.Success("Có lỗi xảy ra");
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Admin/AdminRoles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Admin/AdminRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var role = await _context.Roles.FindAsync(id);
            _context.Roles.Remove(role);
            await _context.SaveChangesAsync();
            _notyfService.Success("Xóa quyền truy cập thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
            return _context.Roles.Any(e => e.RoleId == id);
        }
    }
}

dapm_final/Areas/Admin/Views/AdminRoles/Create.cshtml
@model dapm_final.Models.Role

@{
    ViewData["Title"] = "Tạo Mới Quyền Truy Cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@* xong *@
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang Chủ</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminRoles" asp-action="Index">Danh Sách Quyền Truy Cập</a>
            <span class="breadcrumb-item active">Tạo Mới Quyền Truy Cập</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông Tin Quyền Truy Cập</h4>
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="RoleName" class="control-label"></label>
                        <input asp-for="RoleName" class="form-control" />
                        <span asp-validation-for="RoleName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Tạo Mới" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

dapm_final/Areas/Admin/Views/AdminRoles/Delete.cshtml
@model dapm_final.Models.Role

@{
    ViewData["Title"] = "Xác Nhận Xóa Quyền Truy Cập " + Model.RoleName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@* xong *@

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang Chủ</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminRoles" asp-action="Index">Danh Sách Quyền Truy Cập</a>
            <span class="breadcrumb-item active">Xác Nhận Xóa Quyền Truy Cập: @Model.RoleName</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông Tin Quyền Truy Cập: @Model.RoleName</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.RoleId</td>
                    </tr>
                    <tr>
                        <td>Tên Quyền Truy Cập:</td>
                        <td>@Model.RoleName</td>
                    </tr>
                    <tr>
                        <td>Mô Tả:</td>
                        <td>@Model.Description</td>
                    </tr>
                    <tr>
                        <td>
                            <form asp-action="Delete" asp-route-id="@Model.RoleId ">
                                <input type="hidden" asp-for="RoleId" />
                                <input type="submit" value="Xác Nhận Xóa" class="btn btn-danger" />
                            </form>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

dapm_final/Areas/Admin/Views/AdminRoles/Details.cshtml
@model dapm_final.Models.Role

@{
    ViewData["Title"] = "Chi Tiết Quyền Truy Cập " + Model.RoleName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang Chủ</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminRoles" asp-action="Index">Danh Sách Quyền Truy Cập</a>
            <span class="breadcrumb-item active">Thông Tin Quyền Truy Cập: @Model.RoleName</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông Tin Quyền Truy Cập: @Model.RoleName</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.RoleId</td>
                    </tr>
                    <tr>
                        <td>Tên Quyền Truy Cập:</td>
                        <td>@Model.RoleName</td>
                    </tr>
                    <tr>
                        <td>Mô Tả:</td>
                        <td>@Model.Description</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

dapm_final/Areas/Admin/Views/AdminRoles/Edit.cshtml
@model dapm_final.Models.Role

@{
    ViewData["Title"] = "Chỉnh Sửa Quyền Truy Cập " + Model.RoleName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@* xong *@
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang Chủ</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminRoles" asp-action="Index">Danh Sách Quyền Truy Cập</a>
            <span class="breadcrumb-item active">Chỉnh Sửa Quyền Truy Cập: @Model.RoleName</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông Tin Quyền Truy Cập: @Model.RoleName</h4>
        <form asp-action="Edit" asp-route-id="@Model.RoleId" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RoleId" />
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="col-sm-2 col-form-label" style="max-width: 30%">RoleName</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" asp-for="RoleName" placeholder="RoleName">
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="col-sm-2 col-form-label" style="max-width: 30%">Description</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" asp-for="Description" placeholder="Description">
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-primary">Chỉnh Sửa</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

dapm_final/Areas/Admin/Views/AdminRoles/Index.cshtml
@model IEnumerable<dapm_final.Models.Role>

@{
    ViewData["Title"] = "Danh Sách Quyền Truy Cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
} @* xong *@

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang Chủ</a>
            <span class="breadcrumb-item active">Danh Sách Quyền Truy Cập</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-md-8">
            </div>
            <div class="col-lg-4 text-right">
                <a class="btn btn-primary" asp-controller="AdminRoles" asp-action="Create"><i class="anticon anticon-plus-circle m-r-5"></i><span>Thêm Quyền</span></a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Tên</th>
                        <th scope="col">Mô Tả</th>
                        <th scope="col">Thao Tác</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <th scope="row">@item.RoleId</th>
                                <td>@item.RoleName</td>
                                <td>@item.Description</td>
                                <td>
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminRoles" asp-action="Details" asp-route-id="@item.RoleId">Chi Tiết</a>
                                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminRoles" asp-action="Edit" asp-route-id="@item.RoleId">Sửa</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminRoles" asp-action="Delete" asp-route-id="@item.RoleId">Xóa</a>

                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>