dapm_final/Areas/Admin/Controllers/AdminCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using dapm_final.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using PagedList.Core;
using dapm_final.Helpper;
using System.IO;

namespace dapm_final.Areas.Admin.Controllers /*xong*/
{
    [Area("Admin")]
    public class AdminCategoriesController : Controller
    {
        private readonly FYProjectContext _context;
        public INotyfService _notyfService { get; }

        public AdminCategoriesController(FYProjectContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminCategories
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20;
            var lsCategorys = _context.Categories
                .AsNoTracking()
                .OrderByDescending(x => x.CatId);
            PagedList<Category> models = new PagedList<Category>(lsCategorys, pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminCategories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CatId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/AdminCategories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CatId,CatName,Description,ParentId,Levels,Ordering,Published,Thumb,Title,Alias,MetaDesc,MetaKey,Cover,SchemaMarkup")] Category category, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                //Xu ly Thumb
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string imageName = Utilities.SEOUrl(category.CatName) + extension;
                    category.Thumb = await Utilities.UploadFile(fThumb, @"category", imageName.ToLower());
                }
                if (string.IsNullOrEmpty(category.Thumb)) category.Thumb = "default.jpg";
                category.Alias = Utilities.SEOUrl(category.CatName);
                _context.Add(category);
                await _context.SaveChangesAsync();
                _notyfService.Success("Thêm mới thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/AdminCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/AdminCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CatId,CatName,Description,ParentId,Levels,Ordering,Published,Thumb,Title,Alias,MetaDesc,MetaKey,Cover,SchemaMarkup")] Category category, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != category.CatId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string imageName = Utilities.SEOUrl(category.CatName) + extension;
                        category.Thumb = await Utilities.UploadFile(fThumb, @"category", imageName.ToLower());
                    }
                    if (string.IsNullOrEmpty(category.Thumb)) category.Thumb = "default.jpg";
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Chỉnh sửa thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CatId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/AdminCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CatId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/AdminCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            var lsProducts = _context.Products.Where(x => x.CatId == category.CatId).ToList();
            foreach (var item in lsProducts)
            {
                var lsOrderDetail = _context.OrderDetails.Where(x => x.ProductId == item.ProductId).ToList();
                foreach (var itemLsOrderDetail in lsOrderDetail)
                {
                    var orderId = _context.Orders.FirstOrDefault(x => x.OrderId == itemLsOrderDetail.OrderId);
                    _context.OrderDetails.Remove(itemLsOrderDetail);
                    _context.Orders.Remove(orderId);
                }
                _context.Products.Remove(item);
            }
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            _notyfService.Success("Xóa thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.CatId == id);
        }
    }
}

dapm_final/Areas/Admin/Views/AdminCategories/Create.cshtml
@model dapm_final.Models.Category

@{
    ViewData["Title"] = "Tạo Mới Danh Mục Sản Phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
} @* xong *@

@section Styles{
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang Chủ</a>
            <a asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" class="breadcrumb-item">Danh Sách Danh Mục</a>
            <span class="breadcrumb-item active">Tạo Mới Danh Mục</span>
        </nav>
    </div>
</div>

<form asp-controller="AdminCategories" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-5">
            </div>
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-plus-circle"></i>
                    <span>Tạo Mới</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN DANH MỤC</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên Danh Mục</label>
                        <input type="text" class="form-control" asp-for="CatName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="ShortDesc">Ordering</label>
                        <input type="text" class="form-control" asp-for="Ordering">
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Ảnh Đại Diện</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>

                    <div class="row">
                        <div class="m-t-25">
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="Published" checked="">
                                    <label for="Published"></label>
                                </div>
                                <label>Public</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Title</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">SchemaMarkup</label>
                        <input type="text" class="form-control" asp-for="SchemaMarkup">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <label class="font-weight-semibold" for="productName">Mô Tả Chi Tiết</label>
                    <textarea class="summernote" asp-for="Description"></textarea>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Adminassets/summernote/summernote-bs4.js"></script>

    <script>

        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
    }

dapm_final/Areas/Admin/Views/AdminCategories/Delete.cshtml
@model dapm_final.Models.Category

@{
    ViewData["Title"] = "Xác Nhận Xoá Danh Mục Sản Phẩm " + Model.CatName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
} @* xong *@

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang Chủ</a>
            <a asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" class="breadcrumb-item">Danh Sách Danh Mục</a>
            <span class="breadcrumb-item active">Xác Nhận Xoá Danh Mục: @Model.CatName</span>
        </nav>
    </div>
</div>

<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height:70px; width:70px">
                <img src="~/images/category/@Model.Thumb" alt="@Model.Title" />
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.CatName</h4>
                <p class="text-muted m-b-0">ID: #@Model.CatId</p>
            </div>
        </div>
        <div class="m-b-15">
            <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@Model.CatId">Chỉnh Sửa</a>
        </div>
    </div>
</div>


<div class="card-body">
    <h4 class="card-title">Thông Tin Danh Mục: @Model.CatName</h4>
    <div class="table-responsive">
        <table class="product-info-table m-t-20">
            <tbody>
                <tr>
                    <td>ID:</td>
                    <td class="text-dark font-weight-semibold">@Model.CatId</td>
                </tr>
                <tr>
                    <td>Tên Danh Mục:</td>
                    <td>@Model.CatName</td>
                </tr>
                <tr>
                    <td>Mô Tả:</td>
                    <td>@Html.Raw(Model.Description)</td>
                </tr>
                <tr>
                    <td>Ordering:</td>
                    <td>@Model.Ordering</td>
                </tr>
                <tr>
                    <td>Public:</td>
                    <td>
                        @if (Model.Published)
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" checked="" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                        else
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                    </td>
                </tr>
                <tr>
                    <td>
                        <form asp-controller="AdminCategories" asp-action="Delete" asp-route-id="@Model.CatId">
                            <input type="hidden" asp-for="CatId" />
                            <input type="submit" value="Xác Nhận Xóa" class="btn btn-danger" />
                        </form>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

dapm_final/Areas/Admin/Views/AdminCategories/Details.cshtml
@model dapm_final.Models.Category

@{
    ViewData["Title"] = "Chi Tiết Danh Mục Sản Phẩm " + Model.CatName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
} @* xong *@

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang Chủ</a>
            <a asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" class="breadcrumb-item">Danh Sách Danh Mục</a>
            <span class="breadcrumb-item active">Thôn Tin Danh Mục: @Model.CatName</span>
        </nav>
    </div>
</div>

<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height:70px; width:70px">
                <img src="~/images/category/@Model.Thumb" alt="@Model.Title" />
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.CatName</h4>
                <p class="text-muted m-b-0">ID: #@Model.CatId</p>
            </div>
        </div>
        <div class="m-b-15">
            <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@Model.CatId">Chỉnh Sửa</a>
        </div>
    </div>
</div>

<div class="card-body">
    <h4 class="card-title">Thông Tin Danh Mục: @Model.CatName</h4>
    <div class="table-responsive">
        <table class="product-info-table m-t-20">
            <tbody>
                <tr>
                    <td>ID:</td>
                    <td class="text-dark font-weight-semibold">@Model.CatId</td>
                </tr>
                <tr>
                    <td>Tên Danh Mục:</td>
                    <td>@Model.CatName</td>
                </tr>
                <tr>
                    <td>Mô Tả:</td>
                    <td>@Html.Raw(Model.Description)</td>
                </tr>
                <tr>
                    <td>Ordering:</td>
                    <td>@Model.Ordering</td>
                </tr>
                <tr>
                    <td>Public:</td>
                    <td>
                        @if (Model.Published)
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" checked="" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                        else
                        {
                            <div class="switch m-r-10">
                                <input type="checkbox" id="switch-1" disabled />
                                <label for="switch-1"></label>
                            </div>
                        }
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

dapm_final/Areas/Admin/Views/AdminCategories/Edit.cshtml
@model dapm_final.Models.Category

@{
    ViewData["Title"] = "Chỉnh Sửa Danh Mục Sản Phẩm " + Model.CatName;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
} @* xong *@

@section Styles{
    <link href="~/Adminassets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Adminassets/summernote/summernote.css" rel="stylesheet" />
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang Chủ</a>
            <a asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" class="breadcrumb-item">Danh Sách Danh Mục</a>
            <span class="breadcrumb-item active">Sửa Danh Mục : @Model.CatName</span>
        </nav>
    </div>
</div>

<form asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@Model.CatId" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="CatId" />
    <input type="hidden" asp-for="Thumb" />
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-5">
            </div>
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>Chỉnh Sửa</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN DANH MỤC</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên Danh Mục</label>
                        <input type="text" class="form-control" asp-for="CatName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="ShortDesc">Ordering</label>
                        <input type="text" class="form-control" asp-for="Ordering">
                    </div>

                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Ảnh Đại Diện</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="m-t-25">
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="Published" checked="">
                                    <label for="Published"></label>
                                </div>
                                <label>Public</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productSize">Title</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">SchemaMarkup</label>
                        <input type="text" class="form-control" asp-for="SchemaMarkup">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <label class="font-weight-semibold" for="productName">Mô Tả Chi Tiết</label>
                    <textarea class="summernote" asp-for="Description"></textarea>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.1/jquery.validate.min.js"></script>
    <script src="~/Adminassets/summernote/summernote-bs4.js"></script>

    <script>

        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
}

dapm_final/Areas/Admin/Views/AdminCategories/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<dapm_final.Models.Category>
@{ int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh Sách Danh Mục Sản Phẩm - Trang " + CurrentPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
} @* xong *@

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang Chủ</a>
            <span class="breadcrumb-item active">Danh Sách Danh Mục - Trang @CurrentPage</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
            </div>
            <div class="col-lg-4 text-right">
                <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminCategories" asp-action="Create"><i class="anticon anticon-plus-circle m-r-5"></i><span>Thêm Danh Mục</span></a>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tên Danh Mục</th>
                        <th>Ordering</th>
                        <th>Trạng Thái</th>
                        <th>Thao Tác</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            string url = $"/{item.Alias}";
                            <tr>
                                <td>@item.CatId</td>
                                <td>@item.CatName</td>
                                <td>@item.Ordering</td>
                                <td>
                                    @if (item.Published == true)
                                    {


                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Public</div>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Non-Public</div>
                                        </div>
                                    }
                                </td>

                                <td>
                                    <a class="btn btn-primary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Details" asp-route-id="@item.CatId">Chi Tiết</a>
                                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@item.CatId">Sửa</a>
                                    <a class="btn btn-success btn-tone m-r-5" asp-area="Admin" asp-controller="AdminCategories" asp-action="Delete" asp-route-id="@item.CatId">Xóa</a>
                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminCategories" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>